worker_processes 1;

events {
    worker_connections 1024;
}

http {

    client_max_body_size 300M;

    include mime.types;
    default_type application/octet-stream;

    include conf.d/maps.conf;
    include conf.d/server.conf;
}