services:

  nginx:
    ports:
      - "${INTERNAL_HOST_PORT:-1235}:80"
    environment:
      NGINX_LOG_LEVEL: "debug"
      OAUTH2_PROXY_AUTH_REQUIRED: "false"
  
  oauth2-proxy:
    environment:
      OAUTH2_PROXY_LOG_LEVEL: "debug"

  media-asset-annotator-server:
    environment:
      LOGGING_LEVEL_ROOT: "DEBUG"
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: "TRACE"
      CORS_ALLOWED_ORIGINS: "http://localhost:1235,http://localhost:5173,http://media-asset-annotator"

  mediacms:
    ports:
      - '${MEDIA_CMS_HOST_PORT:-2080}:80'
    environment:
      DEBUG: "True"
      DO_NOT_TRANSCODE_VIDEO: "True"

  celery-worker:
    deploy:
      replicas: 0

  celery-beat:
    deploy:
      replicas: 0
      
  db-server:
    ports:
        - "7200:7200"

  record-manager-server:
    environment:
      LOGGING_LEVEL_ROOT: "DEBUG"
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: "TRACE"
      security.cors.allowedOrigins: "http://localhost:4173,http://localhost:5173,http://record-manager"

