services:

  nginx:
    image: nginx:latest
    container_name: ${RECORD_SET_NAME:-rm}-gateway
    ports:
      - "${INTERNAL_HOST_PORT:-1235}:80"
    restart: always
    depends_on:
      - record-manager
      - record-manager-server
      - s-pipes-engine
      - db-server
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
      APP_ORIGIN: "${PUBLIC_ORIGIN:-http://localhost:${INTERNAL_HOST_PORT:-1235}}"
      APP_ROOT_PATH: "${APP_ROOT_PATH:-}"
      RECORD_MANAGER_PATH: "${RECORD_MANAGER_PATH:-/record-manager}"
      ANNOTATOR_PATH: "${ANNOTATOR_PATH:-/annotator}"
      MEDIA_CMS_URL: "${PUBLIC_ORIGIN:-http://localhost}:${MEDIA_CMS_HOST_PORT:-2080}"
      ANALYTICS_PATH: "${ANALYTICS_PATH:-/statistics}"
      INTERNAL_RECORD_MANAGER_SERVER_SERVICE: "${INTERNAL_RECORD_MANAGER_SERVER_SERVICE:-http://record-manager-server:8080}"
      INTERNAL_ANNOTATOR_SERVER_SERVICE: "${INTERNAL_ANNOTATOR_SERVER_SERVICE:-http://media-asset-annotator-server}"
      INTERNAL_SPIPES_ENGINE_SERVICE: "${INTERNAL_SPIPES_ENGINE_SERVICE:-http://s-pipes-engine:8080}"
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template:ro
      - ./configs/nginx/error.html:/usr/share/nginx/html/error.html:ro
      - ./configs/nginx/index.html:/usr/share/nginx/html/index.html:ro
      - ./configs/nginx/images:/usr/share/nginx/html/images:ro
      - ./configs/nginx/statistics.html:/usr/share/nginx/html/statistics.html:ro

  oauth2-proxy:
    build:
      context: ./configs/oauth2-proxy
    image: ${RECORD_SET_NAME:-rm}-oauth2-proxy
    container_name: ${RECORD_SET_NAME:-rm}-oauth2-proxy
    restart: always
    depends_on:
      - keycloak-config
      - redis
    expose:
      - "4180"
    volumes:
      - keycloak-secrets:/secrets
    environment:
      OAUTH2_PROXY_PROVIDER: oidc
      OAUTH2_PROXY_CLIENT_ID: media-asset-annotator
      OAUTH2_PROXY_OIDC_ISSUER_URL: "${PUBLIC_ORIGIN:-http://localhost:${INTERNAL_HOST_PORT:-1235}}${APP_ROOT_PATH:-}/services/auth/realms/record-manager"
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_REDIRECT_URL: "${PUBLIC_ORIGIN:-http://localhost:${INTERNAL_HOST_PORT:-1235}}${APP_ROOT_PATH:-}/oauth2/callback"
      OAUTH2_PROXY_ALLOWED_GROUPS: "annotator-access-role"
      OAUTH2_PROXY_OIDC_GROUPS_CLAIM: "realm_access.roles"
      OAUTH2_PROXY_SCOPE: "openid profile email"
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_REVERSE_PROXY: "true"
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
      OAUTH2_PROXY_LOG_LEVEL: debug
      OAUTH2_PROXY_SESSION_STORE_TYPE: redis
      OAUTH2_PROXY_REDIS_CONNECTION_URL: redis://redis:6379
      OAUTH2_PROXY_OIDC_LOGOUT_URL: "${PUBLIC_ORIGIN:-http://localhost:${INTERNAL_HOST_PORT:-1235}}${APP_ROOT_PATH:-}/services/auth/realms/record-manager/protocol/openid-connect/logout"
      OAUTH2_PROXY_COOKIE_SAMESITE: "lax"
      OAUTH2_PROXY_COOKIE_HTTPONLY: "true"
      OAUTH2_PROXY_UPSTREAMS: static://200

  record-manager:
    image: ghcr.io/kbss-cvut/record-manager-ui:latest
    container_name: ${RECORD_SET_NAME:-rm}-record-manager
    expose:
      - "80"
    restart: always
    depends_on:
      - record-manager-server
    environment:
      API_URL: "${PUBLIC_ORIGIN:-http://localhost:${INTERNAL_HOST_PORT:-1235}}${APP_ROOT_PATH:-}/services/record-manager-server"
      APP_INFO: "${RECORD_MANAGER_APP_INFO:-}"
      APP_TITLE: "${RECORD_MANAGER_APP_TITLE:-Record Manager}"
      APP_LANGUAGE: "${APP_LANGUAGE:-en}"
      NAVIGATOR_LANGUAGE: "false"
      BASENAME: "${APP_ROOT_PATH:-}${RECORD_MANAGER_PATH:-/record-manager}"
      AUTHENTICATION: "oidc"
      AUTH_SERVER_URL: "${PUBLIC_ORIGIN:-http://localhost:${INTERNAL_HOST_PORT:-1235}}${APP_ROOT_PATH:-}/services/auth/realms/record-manager"
      AUTH_CLIENT_ID: "record-manager"
      ANALYTICS_URL: "${PUBLIC_ORIGIN:-http://localhost:${INTERNAL_HOST_PORT:-1235}}${APP_ROOT_PATH:-}${ANALYTICS_PATH:-/statistics}"
      EXTENSIONS: "${RECORD_MANAGER_EXTENSIONS:-supplier}"

  record-manager-server:
    image: ghcr.io/kbss-cvut/record-manager:latest
    container_name: ${RECORD_SET_NAME:-rm}-record-manager-server
    expose:
      - "8080"
    restart: always
    depends_on:
      - s-pipes-engine
      - db-server
    environment:
      appContext: "${PUBLIC_ORIGIN:-http://localhost:${INTERNAL_HOST_PORT:-1235}}${APP_ROOT_PATH:-}${RECORD_MANAGER_PATH:-/record-manager}"
      repositoryUrl: "http://db-server:7200/repositories/record-manager-app"
      formGenRepositoryUrl: "http://db-server:7200/repositories/record-manager-formgen"
      formGenServiceUrl: "${FORMGEN_SERVICE_URL:-${INTERNAL_SPIPES_ENGINE_SERVICE:-http://s-pipes-engine:8080}/s-pipes/service?${FORMGEN_SERVICE_QUERY_PARAMS:-_pId=clone-form}}"
      SECURITY_PROVIDER: "oidc"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI: "${PUBLIC_ORIGIN:-http://localhost:${INTERNAL_HOST_PORT:-1235}}${APP_ROOT_PATH:-}/services/auth/realms/record-manager"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI: "http://auth-server:8080/realms/record-manager/protocol/openid-connect/certs"
      SERVER_MAXHTTPREQUESTHEADERSIZE: "40KB"

  s-pipes-engine:
    image: ghcr.io/kbss-cvut/s-pipes/s-pipes-engine:latest
    container_name: ${RECORD_SET_NAME:-rm}-s-pipes-engine
    expose:
      - "8080"
    restart: always
    depends_on:
      - db-server
    environment:
      FORMGEN_REPOSITORY_URL: "http://db-server:7200/repositories/record-manager-formgen"
    volumes:
      - ./configs/s-pipes-engine/scripts:/scripts/root:ro

  media-asset-annotator:
    image: manki1337/media-asset-annotator:latest
    container_name: ${RECORD_SET_NAME:-rm}-media-asset-annotator
    restart: always
    depends_on:
      - media-asset-annotator-server
    environment:
      BASE_PATH: "${APP_ROOT_PATH:-}${ANNOTATOR_PATH:-/annotator}"
      APP_MODE: "prod"
      ANNOTATIONS_API_URL: "${ANNOTATIONS_API_URL:-${PUBLIC_ORIGIN:-http://localhost:1235}${APP_ROOT_PATH:-}/services/annotator-server/annotation/media}"
      MEDIA_ASSET_API_URL: "${MEDIA_ASSET_API_URL:-${PUBLIC_ORIGIN:-http://localhost:1235}${APP_ROOT_PATH:-}/services/annotator-server/asset}"
      MEDIA_ASSETS_LIST_API_URL: "${MEDIA_ASSETS_LIST_API_URL:-${PUBLIC_ORIGIN:-http://localhost:1235}${APP_ROOT_PATH:-}/services/annotator-server/asset/adapter/playlist}"

  media-asset-annotator-server:
    image: manki1337/media-asset-annotator-server:latest
    container_name: ${RECORD_SET_NAME:-rm}-media-asset-annotator-server
    restart: always
    depends_on:
      - db-server
      - s-pipes-engine
    environment:
      SERVER_PORT: 80
      SERVER_CONTEXT_PATH: "/annotator-server"
      MEDIA_CMS_INTERNAL_BASE_URL: "http://mediacms"
      MEDIA_CMS_PUBLIC_BASE_URL: "${PUBLIC_ORIGIN:-http://localhost}:${MEDIA_CMS_HOST_PORT:-2080}"
      MEDIA_CMS_API_BASE: "${MEDIA_CMS_API_BASE:-/api/v1}"
      REPOSITORY_URL: "http://db-server:7200/repositories/record-manager-app"
      DB_USERNAME: "${GDB_USERNAME:-}"
      DB_PASSWORD: "${GDB_PASSWORD:-}"
      CORS_ALLOWED_ORIGINS: "${PUBLIC_ORIGIN:-http://media-asset-annotator,http://localhost:${INTERNAL_HOST_PORT:-1235}}"

  migrations:
    image: mediacms/mediacms:7.2
    container_name: ${RECORD_SET_NAME:-rm}-media-cms-migration
    environment:
      ENABLE_UWSGI: no
      ENABLE_NGINX: no
      ENABLE_CELERY_SHORT: no
      ENABLE_CELERY_LONG: no
      ENABLE_CELERY_BEAT: no
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_NAME: record-manager
      POSTGRES_HOST: postgres
      ADMIN_USER: ${MEDIA_CMS_ADMIN_USER}
      ADMIN_PASSWORD: ${MEDIA_CMS_ADMIN_PASSWORD}
      ADMIN_EMAIL: ${MEDIA_CMS_ADMIN_EMAIL}
    command: ./deploy/docker/prestart.sh
    depends_on:
      - redis
      - postgres
    restart: on-failure

  mediacms:
    build: ./configs/mediacms
    ports:
      - '${MEDIA_CMS_HOST_PORT-2080}:80'
    container_name: ${RECORD_SET_NAME:-rm}-media-cms-web
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/80' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    deploy:
      replicas: 1
    environment:
      ENABLE_CELERY_BEAT: no
      ENABLE_CELERY_SHORT: no
      ENABLE_CELERY_LONG: no
      ENABLE_MIGRATIONS: no
      FRONTEND_HOST: ${PUBLIC_ORIGIN:-http://localhost}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - migrations
      - postgres
      - keycloak-config
    restart: on-failure
    volumes:
      - mediacms-media:/home/mediacms.io/mediacms/media_files
      - keycloak-secrets:/secrets

  celery-beat:
    image: mediacms/mediacms:7.2
    container_name: ${RECORD_SET_NAME:-rm}-media-cms-beat
    environment:
      ENABLE_UWSGI: no
      ENABLE_NGINX: no
      ENABLE_CELERY_SHORT: no
      ENABLE_CELERY_LONG: no
      ENABLE_MIGRATIONS: no
    depends_on:
      - redis
    restart: on-failure
    volumes:
      - mediacms-media:/home/mediacms.io/mediacms/media_files

  celery-worker:
    image: mediacms/mediacms:7.2
    container_name: ${RECORD_SET_NAME:-rm}-media-cms-worker
    deploy:
      replicas: 1
    environment:
      ENABLE_UWSGI: no
      ENABLE_NGINX: no
      ENABLE_CELERY_BEAT: no
      ENABLE_MIGRATIONS: no
    depends_on:
      - migrations
    restart: on-failure
    volumes:
      - mediacms-media:/home/mediacms.io/mediacms/media_files

  redis:
    image: redis
    container_name: ${RECORD_SET_NAME:-rm}-redis
    hostname: norish-redis
    command: redis-server --appendonly yes
    healthcheck:
      test: [ 'CMD-SHELL', 'redis-cli ping || exit 1' ]
    restart: on-failure:5
    volumes:
      - redis-data:/data

  db-server:
    build:
      context: ./configs/db-server
    image: ${RECORD_SET_NAME:-rm}-db-server
    container_name: ${RECORD_SET_NAME:-rm}-db-server
    expose:
      - "7200"
    restart: always
    environment:
      GDB_JAVA_OPTS: "-Dgraphdb.external-url=${PUBLIC_ORIGIN:-http://localhost:${INTERNAL_HOST_PORT:-1235}}${APP_ROOT_PATH:-}/services/db-server"
    volumes:
      - ./configs/db-server/import:/root/graphdb-import:ro
      - db-server:/opt/graphdb/home

  postgres:
    image: postgres:14
    container_name: ${RECORD_SET_NAME:-rm}-postgres
    environment:
      POSTGRES_DB: record-manager
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data

  auth-server:
    image: ghcr.io/kbss-cvut/keycloak-graphdb-user-replicator/keycloak-graphdb:latest
    container_name: ${RECORD_SET_NAME:-rm}-auth-server
    command:
      - start --import-realm --features="token-exchange,admin-fine-grained-authz"
    restart: on-failure:5
    expose:
      - "8080"
    depends_on:
      - postgres
    environment:
      KC_IMPORT: realm-export.json
      KC_HOSTNAME_URL: "${PUBLIC_ORIGIN:-http://localhost:${INTERNAL_HOST_PORT:-1235}}${APP_ROOT_PATH:-}/services/auth/"
      KC_HOSTNAME_ADMIN_URL: "${PUBLIC_ORIGIN:-http://localhost:${INTERNAL_HOST_PORT:-1235}}${APP_ROOT_PATH:-}/services/auth/"
      KC_HTTP_ENABLED: true
      KC_PROXY: edge
      KEYCLOAK_ADMIN: ${KC_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: record-manager
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_SCHEMA: "public"
      DB_SERVER_URL: "http://db-server:7200"
      DB_SERVER_REPOSITORY_ID: "record-manager-app"
      REPOSITORY_LANGUAGE: "en"
      VOCABULARY_USER_TYPE: "http://xmlns.com/foaf/0.1/Person"
      VOCABULARY_USER_FIRST_NAME: "http://xmlns.com/foaf/0.1/firstName"
      VOCABULARY_USER_LAST_NAME: "http://xmlns.com/foaf/0.1/lastName"
      VOCABULARY_USER_USERNAME: "http://xmlns.com/foaf/0.1/accountName"
      VOCABULARY_USER_EMAIL: "http://xmlns.com/foaf/0.1/mbox"
      NAMESPACES: "http://xmlns.com/foaf/0.1/Person/"
      DB_SERVER_CONTEXT: "http://xmlns.com/foaf/0.1/Person/"
      ADD_ACCOUNTS: false
      REALM_ID: "record-manager"
    volumes:
      - auth-server:/opt/keycloak/data
      - ./configs/auth-server:/opt/keycloak/data/import

  keycloak-config:
    image: hashicorp/terraform:light
    container_name: ${RECORD_SET_NAME:-rm}-keycloak-config
    working_dir: /workspace
    entrypoint: ["/workspace/run.sh", "auth-server", "8080", "${KC_REALM}"]
    depends_on:
      - postgres
    environment:
      TF_VAR_kc_admin_user: "${KC_ADMIN_USER}"
      TF_VAR_kc_admin_password: "${KC_ADMIN_PASSWORD}"
      TF_VAR_kc_realm: "${KC_REALM:-record-manager}"
      TF_VAR_kc_url: "http://auth-server:8080/"
      TF_VAR_kc_access_token_lifespan: "${KC_ACCESS_TOKEN_LIFESPAN:-5m}"
      TF_VAR_mediacms_base_url: "${PUBLIC_ORIGIN:-http://localhost}:${MEDIA_CMS_HOST_PORT:-2080}"
      TF_VAR_public_origin: "${PUBLIC_ORIGIN:-http://localhost:${INTERNAL_HOST_PORT:-1235}}"
      TF_VAR_enable_google_login: ${ENABLE_GOOGLE_LOGIN:-false}
      TF_VAR_google_client_id: ${GOOGLE_CLIENT_ID:-}
      TF_VAR_google_client_secret: ${GOOGLE_CLIENT_SECRET:-}
    volumes:
      - ./configs/keycloak-config:/workspace
      - keycloak-secrets:/secrets

volumes:
  db-server:
  auth-server:
  postgres:
  keycloak-secrets:
  mediacms-media:
  redis-data:
