services:

  oauth2-proxy:
    environment:
      OAUTH2_PROXY_LOG_LEVEL: "debug"

  media-asset-annotator-server:
    environment:
      LOGGING_LEVEL_ROOT: "DEBUG"
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: "TRACE"

  mediacms:
    environment:
      DEBUG: "True"
      DO_NOT_TRANSCODE_VIDEO: "True"

  celery-worker:
    deploy:
      replicas: 0

  celery-beat:
    deploy:
      replicas: 0

  record-manager-server:
    environment:
      LOGGING_LEVEL_ROOT: "DEBUG"
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: "TRACE"

