server {
    listen 80;

    gzip on;
    access_log /var/log/nginx/mediacms.io.access.log;
    error_log  /var/log/nginx/mediacms.io.error.log warn;

    location /static {
        alias /home/mediacms.io/mediacms/static;
    }

    # REMOVE direct media alias — route through Django
    location /media/ {
        include /etc/nginx/sites-enabled/uwsgi_params;
        uwsgi_pass 127.0.0.1:9000;
    }

    location / {
        include /etc/nginx/sites-enabled/uwsgi_params;
        uwsgi_pass 127.0.0.1:9000;
    }
}
