server {
    listen 80;

    gzip on;
    access_log /var/log/nginx/mediacms.io.access.log;
    error_log  /var/log/nginx/mediacms.io.error.log warn;

    location /static {
        alias /home/mediacms.io/mediacms/static;
    }

  # Public entry point — goes through Django for auth check
    location /media/ {
        include /etc/nginx/sites-enabled/uwsgi_params;
        uwsgi_pass 127.0.0.1:9000;
    }

    # Internal only — nginx serves file directly after X-Accel-Redirect
    location /protected-media/ {
        internal;                          # blocks direct browser access
        alias /home/mediacms.io/mediacms/media_files/;
    }

    location / {
        include /etc/nginx/sites-enabled/uwsgi_params;
        uwsgi_pass 127.0.0.1:9000;
    }


}
